spring.profiles.active: dev
feed.filename: demo.feed

# Task 4.1: Add audit amount properties for event filtering.
audit.amount:
  deposit: 99
  withdrawal: 99

---

spring:
  profiles: dev
debug: true

---

spring:
  profiles: prod
debug: false
